# Generated by Django 4.0.3 on 2022-04-04 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_rating', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranswer',
            name='answer',
            field=models.CharField(default='', max_length=1024),
        ),
        migrations.AddField(
            model_name='userquestion',
            name='dislikes_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userquestion',
            name='likes_num',
            field=models.IntegerField(default=0),
        ),
    ]
