# Generated by Django 4.0.3 on 2022-04-04 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_rating', '0002_useranswer_answer_userquestion_dislikes_num_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useranswer',
            name='answer',
            field=models.CharField(max_length=1024),
        ),
    ]
