# Generated by Django 4.0.3 on 2022-04-05 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_rating', '0004_rename_tguser_myuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userquestion',
            old_name='user_id',
            new_name='my_user_id',
        ),
    ]
